(()=>{"use strict";
const $=id=>document.getElementById(id), file=$("file"), upload=$("upload"), out=$("out"), name=$("name"), status=$("status"), details=$("details"), warnings=$("warnings"), convert=$("convert"), download=$("download"), preview=$("preview"), screen=$("screen");
let source=null,result=null,base="layout";
upload.onclick=()=>file.click();
file.onchange=()=>{if(file.files[0])load(file.files[0])};
function setStatus(c,t,d){status.className=c;status.textContent=t;details.textContent=d||""}
function load(f){source=f;base=f.name.replace(/\.json$/i,"")||"layout";name.textContent=f.name;out.hidden=false;convert.hidden=true;download.hidden=true;preview.hidden=true;warnings.innerHTML="";
f.text().then(t=>{let d;try{d=JSON.parse(t)}catch(e){setStatus("err","❌ Invalid layout file.","The file is not valid JSON.");return}
if(isNew(d)){result=d;setStatus("ok","✓ This layout is already compatible with Zalith Launcher 2.",count(d)+" controls");showPreview(d);download.hidden=false;return}
if(!isOld(d)){setStatus("err","❌ Unsupported layout format.","The file is not a supported Zalith Launcher 1 / PojavLauncher layout.");return}
setStatus("warn","Detected: Zalith Launcher 1 / PojavLauncher","Press Convert to transform it.");convert.hidden=false;
convert.onclick=()=>{try{result=convertOld(d);setStatus("ok","✓ Conversion successful",result._count+" controls converted");for(const w of result._warnings){const x=document.createElement("div");x.className="warning";x.textContent="⚠ "+w;warnings.appendChild(x)}delete result._count;delete result._warnings;showPreview(result);download.hidden=false;convert.hidden=true}catch(e){setStatus("err","❌ Conversion failed.",e.message)}}
}).catch(()=>setStatus("err","❌ Invalid layout file.","The file could not be read."))}
function isNew(d){return d&&d.editorVersion===12&&d.info&&Array.isArray(d.layers)&&Array.isArray(d.styles)}
function isOld(d){return d&&Array.isArray(d.mControlDataList)}
function count(d){return(d.layers||[]).reduce((n,l)=>n+(l.normalButtons?.length||0)+(l.textBoxes?.length||0)+(l.joystickButtons?.length||0),0)}
const K={32:"GLFW_KEY_SPACE",65:"GLFW_KEY_A",66:"GLFW_KEY_B",67:"GLFW_KEY_C",68:"GLFW_KEY_D",69:"GLFW_KEY_E",70:"GLFW_KEY_F",71:"GLFW_KEY_G",72:"GLFW_KEY_H",73:"GLFW_KEY_I",74:"GLFW_KEY_J",75:"GLFW_KEY_K",76:"GLFW_KEY_L",77:"GLFW_KEY_M",78:"GLFW_KEY_N",79:"GLFW_KEY_O",80:"GLFW_KEY_P",81:"GLFW_KEY_Q",82:"GLFW_KEY_R",83:"GLFW_KEY_S",84:"GLFW_KEY_T",85:"GLFW_KEY_U",86:"GLFW_KEY_V",87:"GLFW_KEY_W",88:"GLFW_KEY_X",89:"GLFW_KEY_Y",90:"GLFW_KEY_Z",256:"GLFW_KEY_ESCAPE",257:"GLFW_KEY_ENTER",258:"GLFW_KEY_TAB",259:"GLFW_KEY_BACKSPACE",260:"GLFW_KEY_INSERT",261:"GLFW_KEY_DELETE",262:"GLFW_KEY_RIGHT",263:"GLFW_KEY_LEFT",264:"GLFW_KEY_DOWN",265:"GLFW_KEY_UP",290:"GLFW_KEY_F1",291:"GLFW_KEY_F2",292:"GLFW_KEY_F3",293:"GLFW_KEY_F4",294:"GLFW_KEY_F5",295:"GLFW_KEY_F6",296:"GLFW_KEY_F7",297:"GLFW_KEY_F8",298:"GLFW_KEY_F9",299:"GLFW_KEY_F10",300:"GLFW_KEY_F11",301:"GLFW_KEY_F12",340:"GLFW_KEY_LEFT_SHIFT",341:"GLFW_KEY_LEFT_CONTROL",342:"GLFW_KEY_LEFT_ALT",344:"GLFW_KEY_RIGHT_SHIFT",345:"GLFW_KEY_RIGHT_CONTROL",346:"GLFW_KEY_RIGHT_ALT"};
function uid(){return crypto.randomUUID?crypto.randomUUID().replaceAll("-",""):Math.random().toString(36).slice(2)+Date.now()}
function tr(v){return{default:v==null||v==="null"?"":String(v),matchQueue:[]}}
function position(b,w){let x=Number(b.x),y=Number(b.y);if(!Number.isFinite(x)){w.push("A control has no numeric x position; it was set to 0.");x=0}if(!Number.isFinite(y)){w.push("A control has no numeric y position; it was set to 0.");y=0}return{x:Math.max(0,Math.min(10000,Math.round(x))),y:Math.max(0,Math.min(10000,Math.round(y)))}}
function events(b,w){const a=[];for(const raw of b.keycodes||[]){const n=Number(raw);if(K[n])a.push({type:"key",key:K[n]});else if(n<0)w.push("A control uses unsupported special keycode "+n+".");else if(n!==0)w.push("A control uses unknown GLFW keycode "+n+".")}return a}
function convertOld(d){const w=[],styles=[],normal=[];for(const b of d.mControlDataList||[]){const sid=uid(),ev=events(b,w),op=Number(b.opacity);const alpha=Number.isFinite(op)?op:1;styles.push({name:"Converted "+sid.slice(0,8),uuid:sid,animateSwap:false,commonStyle:true,lightStyle:{alpha,pressedAlpha:alpha,backgroundColor:0x4d000000,pressedBackgroundColor:0x4d000000,contentColor:0xffffffff,pressedContentColor:0xffffffff,borderWidth:0,pressedBorderWidth:0,borderColor:0xffffffff,pressedBorderColor:0xffffffff,borderRadius:{topStart:0,topEnd:0,bottomEnd:0,bottomStart:0},pressedBorderRadius:{topStart:0,topEnd:0,bottomEnd:0,bottomStart:0}},darkStyle:null});styles[styles.length-1].darkStyle=styles[styles.length-1].lightStyle;
normal.push({text:tr(b.name),uuid:uid(),position:position(b,w),buttonSize:{type:"percentage",widthDp:Number(b.width)||500,heightDp:Number(b.height)||500,widthPercentage:Math.max(100,Math.round((Number(b.width)||500)/10000*10000)),heightPercentage:Math.max(100,Math.round((Number(b.height)||500)/10000*10000)),widthReference:"screen_height",heightReference:"screen_height"},buttonStyle:sid,visibilityType:b.displayInGame&&b.displayInMenu?"always":b.displayInGame?"in_game":"in_menu",clickEvents:ev,isSwipple:!!b.isSwipeable,isPenetrable:!!b.passThruEnabled,isToggleable:!!b.isToggle})}
if((d.mDrawerDataList||[]).length)w.push("Old control drawers are not represented as separate Zalith 2 drawer widgets.");
const i=d.mControlInfoDataList||{},r={info:{name:tr(i.name||base),author:tr(i.author||""),description:tr(i.desc||""),versionCode:0,versionName:String(i.version||"1.0")},layers:[{name:"converted",uuid:uid(),hide:false,hideWhenMouse:true,hideWhenGamepad:true,visibilityType:"always",normalButtons:normal,textBoxes:[],joystickButtons:[]}],styles,joystickStyles:[],editorVersion:12};
Object.defineProperty(r,"_count",{value:normal.length,enumerable:false});Object.defineProperty(r,"_warnings",{value:w,enumerable:false});return r}
function showPreview(d){screen.innerHTML="";for(const l of d.layers||[])for(const b of(l.normalButtons||[]).slice(0,80)){const e=document.createElement("div");e.className="control";e.textContent=b.text?.default||"";e.style.left=(b.position.x/100)+"%";e.style.top=(b.position.y/100)+"%";e.style.width=Math.max(2,(b.buttonSize?.widthPercentage||500)/100)+"%";e.style.height=Math.max(2,(b.buttonSize?.heightPercentage||500)/100)+"%";screen.appendChild(e)}preview.hidden=false}
download.onclick=()=>{if(!result)return;const blob=new Blob([JSON.stringify(result,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=base+"-zalith2.json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
})();